import { DetectLanguage } from "./Tokenizer";

interface LanguageMeta {
    Label: string;
    Color: string;
}

export const LanguageMetaMap: Record<string, LanguageMeta> = {
    luau:       { Label: "Luau",        Color: "#00A2FF" },
    typescript: { Label: "TypeScript",  Color: "#3178C6" },
    javascript: { Label: "JavaScript",  Color: "#F7DF1E" },
    rust:       { Label: "Rust",        Color: "#DEA584" },
    css:        { Label: "CSS",         Color: "#1572B6" },
    json:       { Label: "JSON",        Color: "#F5DE19" },
    python:     { Label: "Python",      Color: "#3776AB" },
    html:       { Label: "HTML",        Color: "#E34F26" },
    toml:       { Label: "TOML",        Color: "#9C4221" },
    wgsl:       { Label: "WGSL",        Color: "#6A9FB5" },
    glsl:       { Label: "GLSL",        Color: "#5586A4" },
    markdown:   { Label: "Markdown",    Color: "#7C8A9A" },
    yaml:       { Label: "YAML",        Color: "#CB171E" },
    c:          { Label: "C",           Color: "#A8B9CC" },
    cpp:        { Label: "C++",         Color: "#00599C" },
    go:         { Label: "Go",          Color: "#00ADD8" },
    bash:       { Label: "Bash",        Color: "#4EAA25" },
    sql:        { Label: "SQL",         Color: "#336791" },
    csharp:     { Label: "C#",          Color: "#68217A" },
    java:       { Label: "Java",        Color: "#E76F00" },
    xml:        { Label: "XML",         Color: "#E37933" },
    kotlin:     { Label: "Kotlin",      Color: "#7F52FF" },
    swift:      { Label: "Swift",       Color: "#FA7343" },
    dart:       { Label: "Dart",        Color: "#0175C2" },
    ruby:       { Label: "Ruby",        Color: "#CC342D" },
    php:        { Label: "PHP",         Color: "#777BB4" },
    hlsl:       { Label: "HLSL",        Color: "#5676A7" },
    graphql:    { Label: "GraphQL",     Color: "#E10098" },
    zig:        { Label: "Zig",         Color: "#F7A41D" },
    scala:      { Label: "Scala",       Color: "#DC322F" },
    elixir:     { Label: "Elixir",      Color: "#4B275F" },
    haskell:    { Label: "Haskell",     Color: "#5D4F85" },
    dockerfile: { Label: "Dockerfile",  Color: "#2496ED" },
    makefile:   { Label: "Makefile",    Color: "#A42E2B" },
    nim:        { Label: "Nim",         Color: "#FFE953" },
    vlang:      { Label: "V",           Color: "#5D87BF" },
    red:        { Label: "Red",         Color: "#B32629" },
    j:          { Label: "J",           Color: "#4E6DB2" },
    apl:        { Label: "APL",         Color: "#8A5CF6" },
    factor:     { Label: "Factor",      Color: "#6366F1" },
    idris:      { Label: "Idris",       Color: "#B30000" },
    ocaml:      { Label: "OCaml",       Color: "#EC6813" },
    fsharp:     { Label: "F#",          Color: "#378BBA" },
    erlang:     { Label: "Erlang",      Color: "#A90533" },
    racket:     { Label: "Racket",      Color: "#9F1D20" },
    scheme:     { Label: "Scheme",      Color: "#1E7F4F" },
    lisp:       { Label: "Common Lisp", Color: "#3FB68B" },
    fortran:    { Label: "Fortran",     Color: "#734F96" },
    cobol:      { Label: "COBOL",       Color: "#005CA5" },
    ada:        { Label: "Ada",         Color: "#02A676" },
    crystal:    { Label: "Crystal",     Color: "#776791" },
    julia:      { Label: "Julia",       Color: "#9558B2" },
    r:          { Label: "R",           Color: "#276DC3" },
    perl:       { Label: "Perl",        Color: "#39457E" },
    powershell: { Label: "PowerShell",  Color: "#5391FE" },
    batch:      { Label: "Batch",       Color: "#4EAA25" },
    objectivec: { Label: "Objective-C", Color: "#438EFF" },
    matlab:     { Label: "MATLAB",      Color: "#E16737" },
    groovy:     { Label: "Groovy",      Color: "#4298B8" },
    gradle:     { Label: "Gradle",      Color: "#02303A" },
    clojure:    { Label: "Clojure",     Color: "#5881D8" },
    coffee:     { Label: "CoffeeScript", Color: "#244776"},
    elm:        { Label: "Elm",         Color: "#60B5CC" },
    purescript: { Label: "PureScript",  Color: "#1D222D" },
    rescript:   { Label: "ReScript",    Color: "#E6484F" },
    reason:     { Label: "Reason",      Color: "#DD4B39" },
    qml:        { Label: "QML",         Color: "#41CD52" },
    vala:       { Label: "Vala",        Color: "#7239B3" },
    pascal:     { Label: "Pascal",      Color: "#B0CE4E" },
    dlang:      { Label: "D",           Color: "#BA595E" },
    assembly:   { Label: "Assembly",    Color: "#6E4C13" },
    llvm:       { Label: "LLVM",        Color: "#185619" },
    cuda:       { Label: "CUDA",        Color: "#76B900" },
    opencl:     { Label: "OpenCL",      Color: "#ED1C24" },
    metal:      { Label: "Metal",       Color: "#8A8A8A" },
    shaderlab:  { Label: "ShaderLab",   Color: "#222C37" },
    scss:       { Label: "SCSS",        Color: "#CD6799" },
    sass:       { Label: "Sass",        Color: "#CF649A" },
    less:       { Label: "Less",        Color: "#1D365D" },
    vue:        { Label: "Vue",         Color: "#41B883" },
    svelte:     { Label: "Svelte",      Color: "#FF3E00" },
    astro:      { Label: "Astro",       Color: "#FF5D01" },
    mdx:        { Label: "MDX",         Color: "#1B1F24" },
    solidity:   { Label: "Solidity",    Color: "#363636" },
    move:       { Label: "Move",        Color: "#4A6CF7" },
    cairo:      { Label: "Cairo",       Color: "#FF4A7A" },
    vyper:      { Label: "Vyper",       Color: "#2980B9" },
    terraform:  { Label: "Terraform",   Color: "#7B42BC" },
    hcl:        { Label: "HCL",         Color: "#844FBA" },
    nix:        { Label: "Nix",         Color: "#5277C3" },
    cue:        { Label: "CUE",         Color: "#5886E1" },
    dhall:      { Label: "Dhall",       Color: "#DF9300" },
    protobuf:   { Label: "Protocol Buffers", Color: "#4285F4" },
    thrift:     { Label: "Thrift",      Color: "#D12127" },
    capnp:      { Label: "Cap'n Proto", Color: "#C9B37E" },
    avro:       { Label: "Avro",        Color: "#7F52FF" },
    wasm:       { Label: "WebAssembly", Color: "#654FF0" },
    webidl:     { Label: "Web IDL",     Color: "#005A9C" },
    cmake:      { Label: "CMake",       Color: "#064F8C" },
    meson:      { Label: "Meson",       Color: "#007800" },
    bazel:      { Label: "Bazel",       Color: "#43A047" },
    starlark:   { Label: "Starlark",    Color: "#76D275" },
    ini:        { Label: "INI",         Color: "#D1B654" },
    env:        { Label: "Environment", Color: "#ECD53F" },
    properties: { Label: "Properties",  Color: "#AAB2BF" },
    csv:        { Label: "CSV",         Color: "#4CAF50" },
    latex:      { Label: "LaTeX",       Color: "#008080" },
    bibtex:     { Label: "BibTeX",      Color: "#778899" },
    gdscript:   { Label: "GDScript",    Color: "#478CBF" },
    hack:       { Label: "Hack",        Color: "#878787" },
    vb:         { Label: "Visual Basic", Color: "#945DB7" },
    vbscript:   { Label: "VBScript",    Color: "#15DCDC" },
    raku:       { Label: "Raku",        Color: "#0000FB" },
    tcl:        { Label: "Tcl",         Color: "#D6B656" },
    abap:       { Label: "ABAP",        Color: "#E8274B" },
    apex:       { Label: "Apex",        Color: "#1797C0" },
    sas:        { Label: "SAS",         Color: "#B34936" },
    stata:      { Label: "Stata",       Color: "#1A5FB4" },
    wolfram:    { Label: "Wolfram",     Color: "#DD1100" },
    smalltalk:  { Label: "Smalltalk",   Color: "#596706" },
    prolog:     { Label: "Prolog",      Color: "#74283C" },
    mercury:    { Label: "Mercury",     Color: "#FF2B2B" },
    janet:      { Label: "Janet",       Color: "#0886A5" },
    gleam:      { Label: "Gleam",       Color: "#FFAFF3" },
    prisma:     { Label: "Prisma",      Color: "#2D3748" },
    ron:        { Label: "RON",         Color: "#9C6ADE" },
    kdl:        { Label: "KDL",         Color: "#FFB300" },
    brainfuck:  { Label: "Brainfuck",   Color: "#9CA3AF" },
    whitespace: { Label: "Whitespace",  Color: "#D1D5DB" },
    lolcode:    { Label: "LOLCODE",     Color: "#F6C344" },
    befunge:    { Label: "Befunge",     Color: "#C084FC" },
    chef:       { Label: "Chef",        Color: "#D97706" },
    plain:      { Label: "Plain Text",  Color: "#8B93A7" },
};

const FileNameLanguages: Record<string, string> = {
    "dockerfile": "dockerfile",
    "containerfile": "dockerfile",
    "makefile": "makefile",
    "gnumakefile": "makefile",
    "cmakelists.txt": "cmake",
    "meson.build": "meson",
    "meson_options.txt": "meson",
    "build": "bazel",
    "build.bazel": "bazel",
    "workspace": "bazel",
    "workspace.bazel": "bazel",
    "module.bazel": "bazel",
    "rakefile": "ruby",
    "gemfile": "ruby",
    "podfile": "ruby",
    "brewfile": "ruby",
    "vagrantfile": "ruby",
    "justfile": "makefile",
    "procfile": "properties",
    ".env": "env",
    ".env.local": "env",
    ".env.development": "env",
    ".env.production": "env",
    ".env.test": "env",
    ".editorconfig": "ini",
    ".gitignore": "git",
    ".gitattributes": "git",
    ".gitmodules": "git",
};

const FileExtLanguages: Record<string, string> = {
    ts: "typescript", tsx: "typescript", mts: "typescript", cts: "typescript",
    js: "javascript", jsx: "javascript", mjs: "javascript", cjs: "javascript",
    py: "python", pyw: "python", pyi: "python", ipynb: "python",
    rb: "ruby", rake: "ruby", gemspec: "ruby",
    php: "php", phtml: "php",
    ps1: "powershell", psm1: "powershell", psd1: "powershell",
    bat: "batch", cmd: "batch",
    r: "r", rmd: "r", qmd: "r",
    pl: "perl", pm: "perl", t: "perl", pod: "perl",
    m: "objectivec", mm: "objectivec",
    jl: "julia",
    mlx: "matlab", mat: "matlab",
    groovy: "groovy", gvy: "groovy", gradle: "gradle",
    clj: "clojure", cljs: "clojure", cljc: "clojure", edn: "clojure",
    coffee: "coffee", cson: "coffee", litcoffee: "coffee",
    elm: "elm",
    purs: "purescript",
    res: "rescript", resi: "rescript",
    re: "reason", rei: "reason",
    qml: "qml",
    vala: "vala", vapi: "vala",
    pas: "pascal", pp: "pascal", inc: "pascal",
    d: "dlang", di: "dlang",
    asm: "assembly", s: "assembly", nasm: "assembly",
    ll: "llvm",
    cu: "cuda", cuh: "cuda",
    cl: "opencl", opencl: "opencl",
    metal: "metal",
    shader: "shaderlab", shadergraph: "shaderlab",
    scss: "scss", sass: "sass", less: "less",
    vue: "vue", svelte: "svelte", astro: "astro", mdx: "mdx",
    sol: "solidity",
    move: "move",
    cairo: "cairo",
    vy: "vyper",
    tf: "terraform", tfvars: "terraform",
    hcl: "hcl",
    nix: "nix",
    cue: "cue",
    dhall: "dhall",
    proto: "protobuf", prototxt: "protobuf",
    thrift: "thrift",
    capnp: "capnp",
    avro: "avro",
    wat: "wasm", wast: "wasm", wasm: "wasm",
    webidl: "webidl",
    cmake: "cmake",
    bzl: "starlark", star: "starlark",
    ini: "ini", cfg: "ini", conf: "ini",
    env: "env",
    properties: "properties",
    csv: "csv", tsv: "csv",
    tex: "latex", sty: "latex", cls: "latex",
    bib: "bibtex",
    gd: "gdscript", tres: "gdscript", tscn: "gdscript",
    hh: "hack", hhi: "hack",
    vb: "vb", vbs: "vbscript",
    raku: "raku", rakumod: "raku", rakutest: "raku", p6: "raku", pm6: "raku",
    tcl: "tcl", tk: "tcl",
    abap: "abap",
    trigger: "apex",
    sas: "sas",
    do: "stata", ado: "stata",
    wl: "wolfram", wls: "wolfram", nb: "wolfram",
    st: "smalltalk",
    pro: "prolog", prolog: "prolog",
    janet: "janet",
    gleam: "gleam",
    prisma: "prisma",
    ron: "ron",
    kdl: "kdl",
    lol: "lolcode", lols: "lolcode",
};

const AssetExtColors: Record<string, string> = {
    obj: "#E8906A",
    fbx: "#E8906A",
    gltf: "#E8906A",
    glb: "#E8906A",
    blend: "#E8906A",
    dae: "#E8906A",
    stl: "#E8906A",
    ply: "#E8906A",
};

const AssetExtLabels: Record<string, string> = {
    obj: "3D Model",
    fbx: "3D Model",
    gltf: "3D Model",
    glb: "3D Model",
    blend: "Blender",
    dae: "3D Model",
    stl: "3D Model",
    ply: "3D Model",
};

function GetBaseName(FileName: string): string {
    return FileName.split(/[\\/]/).pop()?.toLowerCase() ?? FileName.toLowerCase();
}

function GetExt(FileName: string): string {
    return GetBaseName(FileName).split(".").pop()?.toLowerCase() ?? "";
}

function GetFileMetaLanguage(FileName: string): string {
    const Base = GetBaseName(FileName);
    const Ext = GetExt(FileName);
    return FileNameLanguages[Base] ?? FileExtLanguages[Ext] ?? DetectLanguage(FileName);
}

export function GetLanguageLabel(Language: string): string {
    return LanguageMetaMap[Language]?.Label ?? LanguageMetaMap.plain.Label;
}

export function GetLanguageColor(Language: string): string {
    return LanguageMetaMap[Language]?.Color ?? LanguageMetaMap.plain.Color;
}

export function GetFileLanguage(FileName: string): string {
    return DetectLanguage(FileName);
}

export function GetFileLanguageLabel(FileName: string): string {
    const Ext = GetExt(FileName);
    return AssetExtLabels[Ext] ?? GetLanguageLabel(GetFileMetaLanguage(FileName));
}

export function GetFileLanguageColor(FileName: string): string {
    const Ext = GetExt(FileName);
    return AssetExtColors[Ext] ?? GetLanguageColor(GetFileMetaLanguage(FileName));
}
